// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_2MdItjl2Xh_pwUGN-h0L4Kqc2GEuf8',
    appId: '1:788420646144:android:b21d32373d350059f74fe5',
    messagingSenderId: '788420646144',
    projectId: 'login-b6259',
    storageBucket: 'login-b6259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKUbie_Y5TZqLexHy1kF7QVNoekJNFnX0',
    appId: '1:788420646144:ios:1b4b9dcb0c988367f74fe5',
    messagingSenderId: '788420646144',
    projectId: 'login-b6259',
    storageBucket: 'login-b6259.appspot.com',
    androidClientId: '788420646144-g7s3d1qjr3m0b8c7ij1kbg5p0e5r4uvf.apps.googleusercontent.com',
    iosClientId: '788420646144-mpuat41aqu7ccr12aj5mopk08coa7sol.apps.googleusercontent.com',
    iosBundleId: 'com.example.sideApp',
  );
}
